---
name: "Semantic PR and Commit Messages"

# yamllint disable-line rule:truthy
on:
  pull_request:
    types: [opened, reopened, synchronize, edited]

jobs:
  semantic:
    uses: influxdata/validate-semantic-github-messages/.github/workflows/semantic.yml@main
